name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/torizon/rac-ci:a190170
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: tzn-rac-default-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            tzn-rac-default
      - run: git config --global --add safe.directory $PWD
      - run: cargo test -- --nocapture

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    container:
      image: pergamos/rac-ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: tzn-rac-default-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            tzn-rac-default-
      - run: git config --global --add safe.directory $PWD
      - run: cargo clippy -- -Wclippy::pedantic
      - run: cargo fmt --check

  build-armv7:
    name: Build armv7
    runs-on: ubuntu-24.04
    container:
      image: pergamos/rac-ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: tzn-rac-armv7-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            tzn-rac-armv7
      - run: git config --global --add safe.directory $PWD
      - run: cargo build --release --target armv7-unknown-linux-musleabihf
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: rac-armv7
          path: target/armv7-unknown-linux-musleabihf/release/rac

  build-aarch64:
    name: Build aarch64
    runs-on: ubuntu-24.04
    container:
      image: pergamos/rac-ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: tzn-rac-aarch64-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            tzn-rac-aarch64
      - run: git config --global --add safe.directory $PWD
      - run: cargo build --release --target aarch64-unknown-linux-musl
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: rac-aarch64
          path: target/aarch64-unknown-linux-musl/release/rac

  build-amd64:
    name: Build amd64
    runs-on: ubuntu-24.04
    container:
      image: pergamos/rac-ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: tzn-rac-amd64-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            tzn-rac-amd64
      - run: git config --global --add safe.directory $PWD
      - run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: rac-amd64
          path: target/x86_64-unknown-linux-musl/release/rac

  release:
    name: Release
    runs-on: ubuntu-24.04
    needs: [ build-armv7, build-aarch64, build-amd64 ]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Download armv7 binary
        uses: actions/download-artifact@v4
        with:
          name: rac-armv7
          path: artifacts/armv7

      - name: Download aarch64 binary
        uses: actions/download-artifact@v4
        with:
          name: rac-aarch64
          path: artifacts/aarch64

      - name: Download amd64 binary
        uses: actions/download-artifact@v4
        with:
          name: rac-amd64
          path: artifacts/amd64

      - name: Rename binaries
        run: |
          mv artifacts/armv7/rac artifacts/armv7/rac-armv7
          mv artifacts/aarch64/rac artifacts/aarch64/rac-aarch64
          mv artifacts/amd64/rac artifacts/amd64/rac-amd64

      - name: Create GitHub release with assets
        run: |
          VERSION=$(cat VERSION)
          gh repo set-default gaiaBuildSystem/rac
          gh release create $VERSION \
            --target main \
            -t "PhobOS rac $VERSION" \
            -n "PhobOS rac $VERSION" \
            artifacts/armv7/rac-armv7 \
            artifacts/aarch64/rac-aarch64 \
            artifacts/amd64/rac-amd64
